/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon Nash
 */
public class JPanelFuncionesAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFuncionesAdministrador
     */
    public JPanelFuncionesAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFunciones = new javax.swing.JPanel();
        jbttnIniciaRegistro = new javax.swing.JButton();
        jbttnFinalizaRegistro = new javax.swing.JButton();
        jbttnAceptaCandidatos = new javax.swing.JButton();
        jbttnAsignaPrivilegios = new javax.swing.JButton();
        jbttnAsignarAsesorGrupo = new javax.swing.JButton();
        jbttnSalir = new javax.swing.JButton();

        jPanelFunciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Funciones Administrador"));

        jbttnIniciaRegistro.setText("Inicia Registro a Seminario");

        jbttnFinalizaRegistro.setText("Finaliza Registro a Seminario");

        jbttnAceptaCandidatos.setText("Acepta Candidatos");

        jbttnAsignaPrivilegios.setText("Asignar Privilegios");

        jbttnAsignarAsesorGrupo.setText("Asignar Asesores y Grupos");

        javax.swing.GroupLayout jPanelFuncionesLayout = new javax.swing.GroupLayout(jPanelFunciones);
        jPanelFunciones.setLayout(jPanelFuncionesLayout);
        jPanelFuncionesLayout.setHorizontalGroup(
            jPanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbttnIniciaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttnFinalizaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jbttnAceptaCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttnAsignaPrivilegios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttnAsignarAsesorGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelFuncionesLayout.setVerticalGroup(
            jPanelFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbttnIniciaRegistro)
                .addGap(16, 16, 16)
                .addComponent(jbttnFinalizaRegistro)
                .addGap(18, 18, 18)
                .addComponent(jbttnAceptaCandidatos)
                .addGap(18, 18, 18)
                .addComponent(jbttnAsignaPrivilegios)
                .addGap(18, 18, 18)
                .addComponent(jbttnAsignarAsesorGrupo)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jbttnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jbttnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbttnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelFunciones;
    private javax.swing.JButton jbttnAceptaCandidatos;
    private javax.swing.JButton jbttnAsignaPrivilegios;
    private javax.swing.JButton jbttnAsignarAsesorGrupo;
    private javax.swing.JButton jbttnFinalizaRegistro;
    private javax.swing.JButton jbttnIniciaRegistro;
    private javax.swing.JButton jbttnSalir;
    // End of variables declaration//GEN-END:variables
}
