/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon Nash
 */
public class JPanelRegistroAsesor extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRegistroAsesor
     */
    public JPanelRegistroAsesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabNomAsesor = new javax.swing.JLabel();
        jlblApellidoPaterno = new javax.swing.JLabel();
        jlblApellicoMaterno = new javax.swing.JLabel();
        jblCorrEletrAsesor = new javax.swing.JLabel();
        jlblTelefono = new javax.swing.JLabel();
        jtxtNombreAsesor = new javax.swing.JTextField();
        jtxtApellidoPaterno = new javax.swing.JTextField();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jtxtCorrEleAsesor = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabCubiculo = new javax.swing.JLabel();
        jtxtCubiculo = new javax.swing.JTextField();
        jLabHrAsesor = new javax.swing.JLabel();
        jbttnCrearAsesorias = new javax.swing.JButton();
        jPanelCondicionesUso = new javax.swing.JPanel();
        jRdBttnCondicionesSi = new javax.swing.JRadioButton();
        jRdBttnCondicionesNo = new javax.swing.JRadioButton();
        jbttnCancelar = new javax.swing.JButton();
        jbttnGuardar = new javax.swing.JButton();
        jPanelAceptarCandidatos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabNomAsesor.setText("Nombre");

        jlblApellidoPaterno.setText("Apellido Paterno");

        jlblApellicoMaterno.setText("Apellido Materno");

        jblCorrEletrAsesor.setText("Correo electronico ");

        jlblTelefono.setText("Telefono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabNomAsesor)
                        .addGap(75, 75, 75)
                        .addComponent(jtxtNombreAsesor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblApellidoPaterno)
                        .addGap(34, 34, 34)
                        .addComponent(jtxtApellidoPaterno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblApellicoMaterno)
                        .addGap(32, 32, 32)
                        .addComponent(jtxtApellidoMaterno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblCorrEletrAsesor)
                            .addComponent(jlblTelefono))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTelefono)
                            .addComponent(jtxtCorrEleAsesor))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNomAsesor)
                    .addComponent(jtxtNombreAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblApellidoPaterno)
                    .addComponent(jtxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblApellicoMaterno)
                    .addComponent(jtxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblCorrEletrAsesor)
                    .addComponent(jtxtCorrEleAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTelefono)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Laborales"));

        jLabCubiculo.setText("Cubiculo");

        jtxtCubiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCubiculoActionPerformed(evt);
            }
        });

        jLabHrAsesor.setText("Horario de asesorias");

        jbttnCrearAsesorias.setText("Crear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabCubiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabHrAsesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttnCrearAsesorias, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabCubiculo)
                    .addComponent(jtxtCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabHrAsesor)
                    .addComponent(jbttnCrearAsesorias))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCondicionesUso.setBorder(javax.swing.BorderFactory.createTitledBorder("Acetpto terminos y condiciones de uso"));

        jRdBttnCondicionesSi.setText("si");

        jRdBttnCondicionesNo.setText("no");

        javax.swing.GroupLayout jPanelCondicionesUsoLayout = new javax.swing.GroupLayout(jPanelCondicionesUso);
        jPanelCondicionesUso.setLayout(jPanelCondicionesUsoLayout);
        jPanelCondicionesUsoLayout.setHorizontalGroup(
            jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondicionesUsoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jRdBttnCondicionesSi)
                .addGap(47, 47, 47)
                .addComponent(jRdBttnCondicionesNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCondicionesUsoLayout.setVerticalGroup(
            jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondicionesUsoLayout.createSequentialGroup()
                .addGroup(jPanelCondicionesUsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdBttnCondicionesSi)
                    .addComponent(jRdBttnCondicionesNo))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jbttnCancelar.setText("Cancelar");

        jbttnGuardar.setText("Guardar");

        jPanelAceptarCandidatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos de Administrador"));

        jButton1.setText("Administrar Seminario");

        javax.swing.GroupLayout jPanelAceptarCandidatosLayout = new javax.swing.GroupLayout(jPanelAceptarCandidatos);
        jPanelAceptarCandidatos.setLayout(jPanelAceptarCandidatosLayout);
        jPanelAceptarCandidatosLayout.setHorizontalGroup(
            jPanelAceptarCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAceptarCandidatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        jPanelAceptarCandidatosLayout.setVerticalGroup(
            jPanelAceptarCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptarCandidatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCondicionesUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbttnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbttnGuardar))
                    .addComponent(jPanelAceptarCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAceptarCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCondicionesUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbttnCancelar)
                            .addComponent(jbttnGuardar))
                        .addGap(36, 36, 36))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCubiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCubiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCubiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabCubiculo;
    private javax.swing.JLabel jLabHrAsesor;
    private javax.swing.JLabel jLabNomAsesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAceptarCandidatos;
    private javax.swing.JPanel jPanelCondicionesUso;
    private javax.swing.JRadioButton jRdBttnCondicionesNo;
    private javax.swing.JRadioButton jRdBttnCondicionesSi;
    private javax.swing.JLabel jblCorrEletrAsesor;
    private javax.swing.JButton jbttnCancelar;
    private javax.swing.JButton jbttnCrearAsesorias;
    private javax.swing.JButton jbttnGuardar;
    private javax.swing.JLabel jlblApellicoMaterno;
    private javax.swing.JLabel jlblApellidoPaterno;
    private javax.swing.JLabel jlblTelefono;
    private javax.swing.JTextField jtxtApellidoMaterno;
    private javax.swing.JTextField jtxtApellidoPaterno;
    private javax.swing.JTextField jtxtCorrEleAsesor;
    private javax.swing.JTextField jtxtCubiculo;
    private javax.swing.JTextField jtxtNombreAsesor;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
