/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jhon Nash
 */
public class JPanelRegistroCandidato extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRegistroCandidato
     */
    public JPanelRegistroCandidato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosPersonales = new javax.swing.JPanel();
        jlabNombre = new javax.swing.JLabel();
        jLabApPaterno = new javax.swing.JLabel();
        jLabApMaterno = new javax.swing.JLabel();
        jLabCorrElectronico = new javax.swing.JLabel();
        jLabTelCelular = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellidoPaterno = new javax.swing.JTextField();
        jtxtApellidoMaterno = new javax.swing.JTextField();
        jtxtCorrElectronico = new javax.swing.JTextField();
        jtxtNumTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabMatricula = new javax.swing.JLabel();
        jLabCarrera = new javax.swing.JLabel();
        jLabGeneracion = new javax.swing.JLabel();
        jLabNomTesis = new javax.swing.JLabel();
        jLabDircTesis = new javax.swing.JLabel();
        jtxtMatricula = new javax.swing.JTextField();
        jtxtGeneracion = new javax.swing.JTextField();
        jComBoxCarrera = new javax.swing.JComboBox<>();
        jtxtNomTesis = new javax.swing.JTextField();
        jtxtDircTesis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabTrabajo = new javax.swing.JLabel();
        jRadBtSi = new javax.swing.JRadioButton();
        jRadBtnNo = new javax.swing.JRadioButton();
        jLabLugar1 = new javax.swing.JLabel();
        jtxtEntidad = new javax.swing.JTextField();
        jLabHora = new javax.swing.JLabel();
        jbttnHorarioCandidato = new javax.swing.JButton();
        jLabLugar = new javax.swing.JLabel();
        jPanelFotoCandidato = new javax.swing.JPanel();
        jButtonAddFotoCandidato = new javax.swing.JButton();
        jPanelDocumentacion = new javax.swing.JPanel();
        jbttnCartaCompromiso = new javax.swing.JButton();
        jbttnCartaExposicionMotivos = new javax.swing.JButton();
        jPanelCondicionesUso = new javax.swing.JPanel();
        jRdBttnCondicionesSi = new javax.swing.JRadioButton();
        jRdBttnCondicionesNo = new javax.swing.JRadioButton();
        jbttnCancelar = new javax.swing.JButton();
        jbttnGuardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanelDatosPersonales.setFont(new java.awt.Font("Segoe UI Symbol", 1, 11)); // NOI18N
        jPanelDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabNombre.setText("Nombre ");
        jPanelDatosPersonales.add(jlabNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jLabApPaterno.setText("Apellido Paterno");
        jPanelDatosPersonales.add(jLabApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 56, -1, -1));

        jLabApMaterno.setText("Apellido Materno");
        jPanelDatosPersonales.add(jLabApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 82, -1, -1));

        jLabCorrElectronico.setText("Email");
        jPanelDatosPersonales.add(jLabCorrElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 108, -1, -1));

        jLabTelCelular.setText("Telefono Celular");
        jPanelDatosPersonales.add(jLabTelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 134, -1, -1));

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        jPanelDatosPersonales.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 27, 96, -1));
        jPanelDatosPersonales.add(jtxtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 53, 96, -1));
        jPanelDatosPersonales.add(jtxtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 79, 96, -1));
        jPanelDatosPersonales.add(jtxtCorrElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 105, 98, -1));
        jPanelDatosPersonales.add(jtxtNumTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 131, 96, -1));

        add(jPanelDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 160));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Academicos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabMatricula.setText("Matricula");
        jPanel1.add(jLabMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jLabCarrera.setText("Carrera");
        jPanel1.add(jLabCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 88, -1, -1));

        jLabGeneracion.setText("Generacion");
        jPanel1.add(jLabGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, -1, -1));

        jLabNomTesis.setText("Nombre de Tesis");
        jPanel1.add(jLabNomTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 116, -1, -1));

        jLabDircTesis.setText("Director de Tesis");
        jPanel1.add(jLabDircTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));
        jPanel1.add(jtxtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 27, 96, -1));
        jPanel1.add(jtxtGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 52, 96, -1));

        jComBoxCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComBoxCarreraActionPerformed(evt);
            }
        });
        jPanel1.add(jComBoxCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 83, 96, -1));
        jPanel1.add(jtxtNomTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 113, 96, -1));
        jPanel1.add(jtxtDircTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 142, 96, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Laborales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabTrabajo.setText("Trabajas?");
        jPanel2.add(jLabTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, -1, -1));

        jRadBtSi.setText("Si");
        jRadBtSi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtSiActionPerformed(evt);
            }
        });
        jPanel2.add(jRadBtSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 16, -1, -1));

        jRadBtnNo.setText("No");
        jRadBtnNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtnNoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadBtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 16, -1, -1));

        jLabLugar1.setText("Entidad");
        jPanel2.add(jLabLugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, -1, -1));
        jPanel2.add(jtxtEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 43, 74, -1));

        jLabHora.setText("Horarios");
        jPanel2.add(jLabHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 69, -1, -1));

        jbttnHorarioCandidato.setText("Crear");
        jPanel2.add(jbttnHorarioCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 69, 74, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jLabLugar.setText("Lugar");
        add(jLabLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelFotoCandidato.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        jButtonAddFotoCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/addFoto.png"))); // NOI18N

        javax.swing.GroupLayout jPanelFotoCandidatoLayout = new javax.swing.GroupLayout(jPanelFotoCandidato);
        jPanelFotoCandidato.setLayout(jPanelFotoCandidatoLayout);
        jPanelFotoCandidatoLayout.setHorizontalGroup(
            jPanelFotoCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        jPanelFotoCandidatoLayout.setVerticalGroup(
            jPanelFotoCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAddFotoCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        add(jPanelFotoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jPanelDocumentacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentacion"));
        jPanelDocumentacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbttnCartaCompromiso.setText("Carta Compromiso");
        jPanelDocumentacion.add(jbttnCartaCompromiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 61));

        jbttnCartaExposicionMotivos.setText("Carta Exposicion");
        jbttnCartaExposicionMotivos.setMaximumSize(new java.awt.Dimension(121, 23));
        jbttnCartaExposicionMotivos.setMinimumSize(new java.awt.Dimension(121, 23));
        jbttnCartaExposicionMotivos.setPreferredSize(new java.awt.Dimension(121, 23));
        jPanelDocumentacion.add(jbttnCartaExposicionMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, 140, 61));

        add(jPanelDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 210, 160));

        jPanelCondicionesUso.setBorder(javax.swing.BorderFactory.createTitledBorder("Acetpto terminos y condiciones de uso"));
        jPanelCondicionesUso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRdBttnCondicionesSi.setText("si");
        jPanelCondicionesUso.add(jRdBttnCondicionesSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 16, -1, -1));

        jRdBttnCondicionesNo.setText("no");
        jPanelCondicionesUso.add(jRdBttnCondicionesNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 16, -1, -1));

        add(jPanelCondicionesUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 240, 50));

        jbttnCancelar.setText("Cancelar");
        add(jbttnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, -1));

        jbttnGuardar.setText("Guardar");
        add(jbttnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jComBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComBoxCarreraActionPerformed

    }//GEN-LAST:event_jComBoxCarreraActionPerformed

    private void jRadBtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtSiActionPerformed
        /*this.jtxtEntidad.setEditable(true);
        this.jComBoxHora.setEnabled(true);
        this.jRadBtnNo.setSelected(false);
*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadBtSiActionPerformed

    private void jRadBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtnNoActionPerformed
        // TODO add your handling code here:
       /* this.jtxtEntidad.setEditable(false);
        this.jComBoxHora.setEnabled(false);
        this.jRadBtSi.setSelected(false);
*/
    }//GEN-LAST:event_jRadBtnNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddFotoCandidato;
    private javax.swing.JComboBox<String> jComBoxCarrera;
    private javax.swing.JLabel jLabApMaterno;
    private javax.swing.JLabel jLabApPaterno;
    private javax.swing.JLabel jLabCarrera;
    private javax.swing.JLabel jLabCorrElectronico;
    private javax.swing.JLabel jLabDircTesis;
    private javax.swing.JLabel jLabGeneracion;
    private javax.swing.JLabel jLabHora;
    private javax.swing.JLabel jLabLugar;
    private javax.swing.JLabel jLabLugar1;
    private javax.swing.JLabel jLabMatricula;
    private javax.swing.JLabel jLabNomTesis;
    private javax.swing.JLabel jLabTelCelular;
    private javax.swing.JLabel jLabTrabajo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCondicionesUso;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelDocumentacion;
    private javax.swing.JPanel jPanelFotoCandidato;
    private javax.swing.JRadioButton jRadBtSi;
    private javax.swing.JRadioButton jRadBtnNo;
    private javax.swing.JRadioButton jRdBttnCondicionesNo;
    private javax.swing.JRadioButton jRdBttnCondicionesSi;
    private javax.swing.JButton jbttnCancelar;
    private javax.swing.JButton jbttnCartaCompromiso;
    private javax.swing.JButton jbttnCartaExposicionMotivos;
    private javax.swing.JButton jbttnGuardar;
    private javax.swing.JButton jbttnHorarioCandidato;
    private javax.swing.JLabel jlabNombre;
    private javax.swing.JTextField jtxtApellidoMaterno;
    private javax.swing.JTextField jtxtApellidoPaterno;
    private javax.swing.JTextField jtxtCorrElectronico;
    private javax.swing.JTextField jtxtDircTesis;
    private javax.swing.JTextField jtxtEntidad;
    private javax.swing.JTextField jtxtGeneracion;
    private javax.swing.JTextField jtxtMatricula;
    private javax.swing.JTextField jtxtNomTesis;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNumTelefono;
    // End of variables declaration//GEN-END:variables
}
